feat(metriken): rewrite metrics library
pelikan-io/rustcommon pull request #43
Opened 2023-07-14 20:57 UTC by brayniac

A clean reimplementation of the metriken metrics library. That makes some slightly different design choices. Metrics may now have associated metadata and an associated formatter. This allows for adding scoped metrics and to define a particular formatter for each metric.

Overall this adds a lot of flexibility through a richer metrics representation.

2023-07-18 00:38 UTC, swlynch99 requested changes
I haven't fully completed the review but I figure I'll leave some comments before I leave for today.

Some more specific comments on implementation details:
- I think either `name` and `description` should be moved out of the metadata.
- `name` should not be optional.
- `as_any` on the metric trait should return an `Option<&dyn Any>` (as it did before) to reflect whether the metric is active or not.
- `LazyCounter` and `LazyGauge` should be wrappers around `OnceLock<Counter>` and `OnceLock<Gauge>`, respectively, instead of copy-pasting the code.
- The `MetricEntry` trait is rather messy. Instead of returning an owned `HashMap` from `MetricEntry::metadata` it should be probably be something that wraps either the `phf::Map` or the `HashMap`.
- A whole bunch of things used to have docs but don't anymore.

This isn't exhaustive and I'll have to keep reviewing it tomorrow.

In general I don't have huge issues with the new features you've added. I have some smaller issues (as we've already discussed) but they are fixable. However, I feel like the larger rewrite has made the crate less consistent and harder to use. I think we should sit down and try and hash out the design instead of me nitpicking it over github comments.

2023-07-18 15:40 UTC, brayniac commented on metriken/src/metrics/mod.rs
> +}
I actually don't like the previous trait all that much. Let's discuss outside of the review.

2023-07-18 15:46 UTC, brayniac commented on metriken/derive/src/metric.rs
> +        })
Fixed

2023-07-18 15:46 UTC, brayniac commented on metriken/derive/src/args.rs
> +            None => Ok(*self = Some(arg)),
Fixed

2023-07-18 15:46 UTC, brayniac commented on metriken/derive/src/metric.rs
> +        })
Fixed

2023-07-18 15:58 UTC, brayniac commented on metriken/src/lib.rs
> +pub fn deregister_all() {
Removed

2023-07-18 16:03 UTC, brayniac commented on metriken/src/lib.rs
>  }
Done.

2023-07-18 16:03 UTC, brayniac commented on metriken/src/metrics/mod.rs
> +    }
This isn't needed. Removed.

2023-07-18 16:12 UTC, brayniac commented on metriken/src/counters/standard.rs
> +}
Done.

2023-07-18 17:34 UTC, brayniac commented on metriken/src/metrics/dynamic/registry.rs
> +    metrics: RwLock<Vec<DynamicEntry>>,
Done.

2023-07-24 18:50 UTC, brayniac commented
Closing this as the changes needed were made across several smaller PRs.

2023-07-24 18:50 UTC, closed without merging